### ISSUE TITLE
OOM with the upscale even on 512 with 16G 

### ISSUE THREAD

**Issue by Wprussell** [Haoming02/comfyui-old-photo-restoration#4]
Seems like there is no CPU failover implemented... Even though... 16 Is Huge for this....   I know you are limited by the architecture. But if you can somehow improve the memory management This would be fantastic.   So much simpler and cleaner then BOPBTL

!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "C:\AI\ComfyUI\comfyui\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\comfyui\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\comfyui\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\AI\ComfyUI\comfyui\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-old-photo-restoration\nodes.py", line 95, in test
    output: Image = global_test(
                    ^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-old-photo-restoration\Global\test.py", line 139, in global_test
    generated = model.inference(input_image, mask)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-old-photo-restoration\Global\models\mapping_model.py", line 439, in inference
    label_feat_map = self.mapping_net.inference_forward(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-old-photo-restoration\Global\models\NonLocal_feature_mapping_model.py", line 192, in inference_forward
    x2 = self.NL_scale_1.inference_forward(x1, mask)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-old-photo-restoration\Global\models\networks.py", line 772, in inference_forward
    concat_1=torch.cat((z,composed_fold,mask),dim=1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 25.79 seconds

**Comment by Haoming02** [comment]
Set `gpu_id` to `-1` to use CPU

Also, I was able to process a `800x512` image on a RTX 3060 *(12 GB VRAM)* as shown in the README, so not sure what is happening for you.
